const gameConf = {
  "nivell": 1,
  "maxPunts": 1000,
  "velocitatEnemics": 10,
  "intervalAparicioMs": 5000,
  "puntsPerEnemic": 100,
  "maxEnemics": 100,
  "ampleEnemics": 75,
  "altEnemics": 75,
  "nomJugador": "Jowron",
  "puntsJugador": 0,
  "killsJugador": 0,
  "velocitatJugador": 10,
  "ampleJugador": 150,
  "altJugador": 100,
  "maxVides": 3,
  "maxAsteroides": 100,
  "velocitatAsteroides": 10,
}